obj-m += kidnet.o
kidnet-objs := kidnet_main.o
#PWD := $(shell pwd)

all:
	make -C /lib/modules/$(shell uname -r)/build M=$(CURDIR) modules
clean:
	make -C /lib/modules/$(shell uname -r)/build M=$(CURDIR) clean
